"""Initial migration - create all tables

Revision ID: 001
Revises: 
Create Date: 2026-05-14 18:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    
    # Create materials table
    op.create_table('materials',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('material_class', sa.String(), nullable=True),
    sa.Column('fiber_type', sa.String(), nullable=True),
    sa.Column('weave_type', sa.String(), nullable=True),
    sa.Column('coating', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('areal_density_g_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('density_g_cm3', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('tensile_strength_mpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('modulus_gpa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('elongation_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('source_confidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_name'), 'materials', ['name'], unique=False)
    op.create_index(op.f('ix_materials_normalized_name'), 'materials', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_materials_manufacturer'), 'materials', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_materials_material_class'), 'materials', ['material_class'], unique=False)
    
    # Create material_documents table
    op.create_table('material_documents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('material_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('parsed_text', sa.String(), nullable=True),
    sa.Column('manufacturer_detected', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('uploaded_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create ammunition table
    op.create_table('ammunition',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('caliber', sa.String(), nullable=True),
    sa.Column('projectile_type', sa.String(), nullable=True),
    sa.Column('projectile_mass_grains', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('projectile_mass_grams', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('nominal_velocity_fps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nominal_velocity_m_s', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('standard_reference', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create test_sessions table
    op.create_table('test_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=True),
    sa.Column('lab_name', sa.String(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('clay_temperature_c', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ambient_temperature_c', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('conditioning', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create armor_panels table
    op.create_table('armor_panels',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('test_session_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('panel_code', sa.String(), nullable=False),
    sa.Column('vest_type', sa.String(), nullable=True),
    sa.Column('panel_shape', sa.String(), nullable=True),
    sa.Column('panel_width_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('panel_height_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('panel_thickness_mm', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('total_layers', sa.Integer(), nullable=True),
    sa.Column('total_areal_density_g_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_mass_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('construction_notes', sa.String(), nullable=True),
    sa.Column('stitch_pattern', sa.String(), nullable=True),
    sa.Column('curvature', sa.String(), nullable=True),
    sa.Column('backing_material', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create armor_panel_layers table
    op.create_table('armor_panel_layers',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('panel_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('layer_index', sa.Integer(), nullable=False),
    sa.Column('material_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('orientation_degrees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('layer_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['armor_panels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create shot_patterns table
    op.create_table('shot_patterns',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vest_type', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create shot_pattern_positions table
    op.create_table('shot_pattern_positions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('shot_pattern_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('x_normalized', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('y_normalized', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('x_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('y_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('impact_angle_degrees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location_label', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shot_pattern_id'], ['shot_patterns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create shots table
    op.create_table('shots',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('test_session_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('panel_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ammunition_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('shot_pattern_position_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('shot_number', sa.Integer(), nullable=True),
    sa.Column('measured_velocity_fps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('measured_velocity_m_s', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('impact_angle_degrees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bfd_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('penetration', sa.Boolean(), nullable=True),
    sa.Column('partial_penetration', sa.Boolean(), nullable=True),
    sa.Column('trauma_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pass_fail', sa.String(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yaw_observed', sa.Boolean(), nullable=True),
    sa.Column('edge_hit', sa.Boolean(), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=True),
    sa.Column('anomaly_notes', sa.String(), nullable=True),
    sa.Column('raw_source_file', sa.String(), nullable=True),
    sa.Column('raw_row_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ammunition_id'], ['ammunition.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['armor_panels.id'], ),
    sa.ForeignKeyConstraint(['shot_pattern_position_id'], ['shot_pattern_positions.id'], ),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create model_runs table
    op.create_table('model_runs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('training_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_row_count', sa.Integer(), nullable=True),
    sa.Column('formula', sa.String(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create predictions table
    op.create_table('predictions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_run_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('requested_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('predicted_bfd_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prediction_interval_low_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prediction_interval_high_mm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('probability_bfd_gt_44', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('probability_penetration', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('extrapolation_warning', sa.Boolean(), nullable=True),
    sa.Column('comparable_shot_count', sa.Integer(), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create audit_log table
    op.create_table('audit_log',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_table('predictions')
    op.drop_table('model_runs')
    op.drop_table('shots')
    op.drop_table('shot_pattern_positions')
    op.drop_table('shot_patterns')
    op.drop_table('armor_panel_layers')
    op.drop_table('armor_panels')
    op.drop_table('test_sessions')
    op.drop_table('ammunition')
    op.drop_table('material_documents')
    op.drop_index(op.f('ix_materials_material_class'), table_name='materials')
    op.drop_index(op.f('ix_materials_manufacturer'), table_name='materials')
    op.drop_index(op.f('ix_materials_normalized_name'), table_name='materials')
    op.drop_index(op.f('ix_materials_name'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
