"""add hyperparameters_json to model_runs

Revision ID: d1f499d789e3
Revises: 5955366882c6
Create Date: 2026-06-10 10:37:42.669880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1f499d789e3'
down_revision = '5955366882c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_runs', sa.Column('hyperparameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_runs', 'hyperparameters_json')
    # ### end Alembic commands ###
