"""add size_pdfs to geometries

Revision ID: da573ab3ce84
Revises: c3d4e5f6a7b8
Create Date: 2026-08-26 12:38:20.595834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da573ab3ce84'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometries', sa.Column('size_pdfs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geometries', 'size_pdfs')
    # ### end Alembic commands ###
