"""add has_tensile_strength to materials

Revision ID: 6427f90e1fa9
Revises: 20260521_1500
Create Date: 2026-05-22 09:56:24.817916

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6427f90e1fa9'
down_revision = '20260521_1500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_validations')
    op.drop_table('model_performance')
    op.alter_column('materials', 'has_tensile_strength',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('materials', 'has_elongation')
    op.drop_column('materials', 'has_modulus')
    op.drop_constraint('shots_vest_id_fkey', 'shots', type_='foreignkey')
    op.create_foreign_key(None, 'shots', 'vests', ['vest_id'], ['id'])
    op.drop_constraint('test_sessions_vest_id_fkey', 'test_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'test_sessions', 'vests', ['vest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_sessions', type_='foreignkey')
    op.create_foreign_key('test_sessions_vest_id_fkey', 'test_sessions', 'vests', ['vest_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'shots', type_='foreignkey')
    op.create_foreign_key('shots_vest_id_fkey', 'shots', 'vests', ['vest_id'], ['id'], ondelete='SET NULL')
    op.add_column('materials', sa.Column('has_modulus', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('materials', sa.Column('has_elongation', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('materials', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('materials', 'has_tensile_strength',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table('model_performance',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('model_run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metric_value', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True),
    sa.Column('calculated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('data_window', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], name='model_performance_model_run_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_performance_pkey')
    )
    op.create_table('prediction_validations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('prediction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('shot_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('predicted_bfd_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('actual_bfd_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('error_mm', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('validation_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('model_version_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_runs.id'], name='prediction_validations_model_version_id_fkey'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name='prediction_validations_prediction_id_fkey'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name='prediction_validations_shot_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='prediction_validations_pkey')
    )
    # ### end Alembic commands ###
