"""add_geometry_material_config

Revision ID: f8d20fa837ef
Revises: a087df0940b8
Create Date: 2026-06-12 16:11:56.361783

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8d20fa837ef'
down_revision = 'a087df0940b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geometry_material_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('geometry_id', sa.UUID(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('material_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accessories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('efficiency_factor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geometry_material_configs_geometry_id'), 'geometry_material_configs', ['geometry_id'], unique=False)
    op.create_index(op.f('ix_geometry_material_configs_size'), 'geometry_material_configs', ['size'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geometry_material_configs_size'), table_name='geometry_material_configs')
    op.drop_index(op.f('ix_geometry_material_configs_geometry_id'), table_name='geometry_material_configs')
    op.drop_table('geometry_material_configs')
    # ### end Alembic commands ###
