"""replace size_pdfs with pdf_document

Revision ID: 0a7b39e71c16
Revises: da573ab3ce84
Create Date: 2026-08-26 13:06:39.737005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a7b39e71c16'
down_revision = 'da573ab3ce84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometries', sa.Column('pdf_document', sa.JSON(), nullable=True))
    op.drop_column('geometries', 'size_pdfs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometries', sa.Column('size_pdfs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('geometries', 'pdf_document')
    # ### end Alembic commands ###
