"""add_outer_carrier_to_geometry

Revision ID: a087df0940b8
Revises: 07e1a9941d0e
Create Date: 2026-06-12 16:06:02.468559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a087df0940b8'
down_revision = '07e1a9941d0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geometries', sa.Column('outer_carrier_material_id', sa.UUID(), nullable=True))
    op.add_column('geometries', sa.Column('outer_carrier_layer_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geometries', 'outer_carrier_layer_count')
    op.drop_column('geometries', 'outer_carrier_material_id')
    # ### end Alembic commands ###
