"""add has_elongation to materials

Revision ID: a4e319b3bf94
Revises: be88a5f155fe
Create Date: 2026-05-22 09:58:33.961986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e319b3bf94'
down_revision = 'be88a5f155fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('has_elongation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'has_elongation')
    # ### end Alembic commands ###
