"""add has_modulus to materials

Revision ID: be88a5f155fe
Revises: 6427f90e1fa9
Create Date: 2026-05-22 09:57:29.039280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be88a5f155fe'
down_revision = '6427f90e1fa9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('has_modulus', sa.String(), nullable=True))
    op.drop_constraint('fk_shots_vest_id', 'shots', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_shots_vest_id', 'shots', 'vests', ['vest_id'], ['id'], ondelete='SET NULL')
    op.drop_column('materials', 'has_modulus')
    # ### end Alembic commands ###
