"""add_roll_area_to_material

Revision ID: 07e1a9941d0e
Revises: 519b293a83f4
Create Date: 2026-06-12 16:04:48.039784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e1a9941d0e'
down_revision = '519b293a83f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geometries', 'includes_hard_plates',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('materials', sa.Column('roll_area_m2', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'roll_area_m2')
    op.alter_column('geometries', 'includes_hard_plates',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
