"""add_is_female_to_vests

Revision ID: 5955366882c6
Revises: e9215aa04958
Create Date: 2026-06-09 13:41:11.108947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5955366882c6'
down_revision = 'e9215aa04958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'has_elongation')
    op.alter_column('test_sessions', 'is_official',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('vests', sa.Column('is_female', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vests', 'is_female')
    op.alter_column('test_sessions', 'is_official',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('materials', sa.Column('has_elongation', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
